CREATE SEQUENCE ADM_CHECKLIST_ITEM_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;	

CREATE TABLE ADM_CHECKLIST_ITEM ( 
CLI_ID NUMBER DEFAULT ADM_CHECKLIST_ITEM_SEQ.NEXTVAL,
CLITEM_CODE VARCHAR2(50),
CLITEM_NAME NVARCHAR2(255),
CLITEM_DOCSTYPE VARCHAR2(20),
CLITEM_DOCSTYPE_NAME NVARCHAR2(255),
CLITEM_REQUIRE VARCHAR2(20),
CLITEM_REQUIRE_NAME NVARCHAR2(255),
CLITEM_TIME_SUPPLY VARCHAR2(20),
CLITEM_ADDTIME_PRESCRIBED NUMBER,
CLITEM_STATUS NUMBER,
CLITEM_NOTE NVARCHAR2(255),
USER_CREATED VARCHAR2(50),
DATE_CREATED DATE,
USER_UPDATED VARCHAR2(50),
DATE_UPDATED DATE
);

CREATE INDEX ADM_CHECKLIST_ITEM_IDX ON ADM_CHECKLIST_ITEM(CLITEM_CODE);

ALTER TABLE ADM_CHECKLIST_ITEM ADD CONSTRAINT ADM_CHECKLIST_ITEM_PK PRIMARY KEY (CLITEM_CODE)
USING INDEX ADM_CHECKLIST_ITEM_IDX  ENABLE;

COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLG_ID IS '';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_CODE IS 'Mã checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_NAME IS 'Tên checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_DOCSTYPE IS 'Loại chứng từ';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_DOCSTYPE_NAME IS 'Tên loại chứng từ';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_REQUIRE IS 'Bắt buộc';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_REQUIRE_NAME IS 'Bắt buộc (Tên)';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_TIME_SUPPLY IS 'Thời điểm cung cấp';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_ADDTIME_PRESCRIBED IS 'Thời gian bổ sung theo quy định (Ngày)';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_STATUS IS 'Trạng thái';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.CLITEM_NOTE IS 'Ghi chú';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.USER_CREATED IS 'Người tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.DATE_CREATED IS 'Ngày tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.USER_UPDATED IS 'Người cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_ITEM.DATE_UPDATED IS 'Ngày cập nhật';

## Dữ liệu insert sample
Insert into ADM_CHECKLIST_ITEM (CLI_ID,CLITEM_CODE,CLITEM_NAME,CLITEM_DOCSTYPE,CLITEM_DOCSTYPE_NAME,CLITEM_REQUIRE,CLITEM_REQUIRE_NAME,CLITEM_TIME_SUPPLY,CLITEM_ADDTIME_PRESCRIBED,CLITEM_STATUS,CLITEM_NOTE,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED) values (44,'QD13_KHCN_05_04','Biên nhận đã thanh toán/ Xác nhận đã thanh toán công nợ của bên bán hàng (nếu có).','LOAICT02',null,'NO',null,'SGN',30,1,null,'hanhtt',to_date('30-09-2024 13:54:50065','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:54:50065','DD-MM-YYYY HH24:MI:SSSSS'));
Insert into ADM_CHECKLIST_ITEM (CLI_ID,CLITEM_CODE,CLITEM_NAME,CLITEM_DOCSTYPE,CLITEM_DOCSTYPE_NAME,CLITEM_REQUIRE,CLITEM_REQUIRE_NAME,CLITEM_TIME_SUPPLY,CLITEM_ADDTIME_PRESCRIBED,CLITEM_STATUS,CLITEM_NOTE,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED) values (46,'QD13_KHCN_06_02','Văn bản/ Hợp đồng chuyển nhượng BĐS có công chứng/ chứng thực theo quy định của Pháp luật (1)','LOAICT02',null,'YES1',null,'TGN',null,1,null,'hanhtt',to_date('30-09-2024 13:54:50065','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:54:50065','DD-MM-YYYY HH24:MI:SSSSS'));

## Dữ liệu khi query cho bảng này là:
CLGN01_01 | Đề nghị giải ngân/phát hành cam kết bảo lãnh (nếu có) | LOAICT01 | YES1 | TGN
QD13_KHCN_01_01 | Hóa đơn mua hàng (Hóa đơn VAT/ Hóa đơn điện tử/ Hóa đơn bán lẻ). | LOAICT02 | YES1 | TGN