CREATE SEQUENCE ADM_CHECKLIST_GROUP_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE TABLE ADM_CHECKLIST_GROUP ( 
CLG_ID NUMBER DEFAULT ADM_CHECKLIST_GROUP_SEQ.NEXTVAL ,
PRC_CODE VARCHAR2(20),
CLGROUP_TYPE VARCHAR2(20),
CLGROUP_CODE VARCHAR2(50),
CLGROUP_NAME NVARCHAR2(255),
STATUS NUMBER,
CLGROUP_NOTE NVARCHAR2(255),
USER_CREATED VARCHAR2(50),
DATE_CREATED DATE,
USER_UPDATED VARCHAR2(50),
DATE_UPDTAED DATE
);
CREATE INDEX ADM_CHECKLIST_GROUP_IDX ON ADM_CHECKLIST_GROUP (PRC_CODE, CLGROUP_CODE);

CREATE INDEX ADM_CHECKLIST_GROUP_IDX1 ON ADM_CHECKLIST_GROUP ( CLGROUP_CODE);

ALTER TABLE ADM_CHECKLIST_GROUP ADD CONSTRAINT ADM_CHECKLIST_GROUP_PK PRIMARY KEY (PRC_CODE, CLGROUP_CODE)
USING INDEX ADM_CHECKLIST_GROUP_IDX  ENABLE;

COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLG_ID IS 'ID Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.PRC_CODE IS 'Mã quy trình';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_TYPE IS 'Mã loại nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_CODE IS 'Mã Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_NAME IS 'Tên Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.STATUS IS 'Trạng thái';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_NOTE IS 'Ghi chú thêm';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.USER_CREATED IS 'Người tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.DATE_CREATED IS 'Ngày tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.USER_UPDATED IS 'Người cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.DATE_UPDTAED IS 'Ngày cập nhật';