CREATE SEQUENCE ADM_CHECKLIST_GROUP_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE TABLE ADM_CHECKLIST_GROUP ( 
CLG_ID NUMBER DEFAULT ADM_CHECKLIST_GROUP_SEQ.NEXTVAL ,
PRC_CODE VARCHAR2(20),
CLGROUP_TYPE VARCHAR2(20),
CLGROUP_CODE VARCHAR2(50),
CLGROUP_NAME NVARCHAR2(255),
STATUS NUMBER,
CLGROUP_NOTE NVARCHAR2(255),
USER_CREATED VARCHAR2(50),
DATE_CREATED DATE,
USER_UPDATED VARCHAR2(50),
DATE_UPDTAED DATE
);
CREATE INDEX ADM_CHECKLIST_GROUP_IDX ON ADM_CHECKLIST_GROUP (PRC_CODE, CLGROUP_CODE);

CREATE INDEX ADM_CHECKLIST_GROUP_IDX1 ON ADM_CHECKLIST_GROUP ( CLGROUP_CODE);

ALTER TABLE ADM_CHECKLIST_GROUP ADD CONSTRAINT ADM_CHECKLIST_GROUP_PK PRIMARY KEY (PRC_CODE, CLGROUP_CODE)
USING INDEX ADM_CHECKLIST_GROUP_IDX  ENABLE;

COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLG_ID IS 'ID Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.PRC_CODE IS 'Mã quy trình';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_TYPE IS 'Mã loại nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_CODE IS 'Mã Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_NAME IS 'Tên Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.STATUS IS 'Trạng thái';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.CLGROUP_NOTE IS 'Ghi chú thêm';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.USER_CREATED IS 'Người tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.DATE_CREATED IS 'Ngày tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.USER_UPDATED IS 'Người cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_GROUP.DATE_UPDTAED IS 'Ngày cập nhật';

## Dữ liệu insert sample
Insert into ADM_CHECKLIST_GROUP (CLG_ID,PRC_CODE,CLGROUP_TYPE,CLGROUP_CODE,CLGROUP_NAME,CLGROUP_STATUS,CLGROUP_NOTE,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED) values (241,'QT002','LOAINHOMCL05','QD13_KHCN_05','Checklist  Vay vốn lưu động - Giải ngân thanh toán các chi phí dịch vụ',1,null,'hanhtt',to_date('30-09-2024 13:49:49741','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:49:49741','DD-MM-YYYY HH24:MI:SSSSS'));
Insert into ADM_CHECKLIST_GROUP (CLG_ID,PRC_CODE,CLGROUP_TYPE,CLGROUP_CODE,CLGROUP_NAME,CLGROUP_STATUS,CLGROUP_NOTE,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED) values (242,'QT002','LOAINHOMCL05','QD13_KHCN_06','Checklist Vay vốn liên quan BĐS - Nhận chuyển nhượng BĐS đã có GCN và thế chấp BĐS mục đích vay',1,null,'hanhtt',to_date('30-09-2024 13:49:49741','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:49:49741','DD-MM-YYYY HH24:MI:SSSSS'));

## Dữ liệu khi query cho bảng này là:
CLGN01 | Checklist Giải ngân / Phát hành bảo lãnh lần đầu | QT002 | LOAINHOMCL05
QD13_KHCN_01 | Checklist Vay vốn lưu động-Giải ngân thanh toán theo hóa đơn mua hàng | QT002 | LOAINHOMCL05