CREATE SEQUENCE ADM_CHECKLIST_MATRIX_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;		
CREATE TABLE ADM_CHECKLIST_MATRIX ( 
CLI_ID NUMBER DEFAULT ADM_CHECKLIST_MATRIX_SEQ.NEXTVAL,
PRC_CODE	VARCHAR2(20),
CLGROUP_CODE VARCHAR2(50),
CLITEM_CODE VARCHAR2(50),
CLITEM_NAME NVARCHAR2(255),
CLIGM_STATUS	NUMBER,
CLITEM_STATUS NUMBER,
CLIGROUP_STATUS NUMBER,
USER_CREATED VARCHAR2(50),
DATE_CREATED DATE,
USER_UPDATED VARCHAR2(50),
DATE_UPDATED DATE,
CONSTRAINT ADM_CHECKLIST_MATRIX_FK1 FOREIGN KEY (PRC_CODE, CLGROUP_CODE)
        REFERENCES ADM_CHECKLIST_GROUP (PRC_CODE, CLGROUP_CODE) ,
CONSTRAINT ADM_CHECKLIST_MATRIX_FK2 FOREIGN KEY (CLITEM_CODE)
        REFERENCES ADM_CHECKLIST_ITEM (CLITEM_CODE)         
);
CREATE INDEX  ADM_CHECKLIST_MATRIX_IDX ON ADM_CHECKLIST_MATRIX(CLGROUP_CODE, CLITEM_CODE);
CREATE INDEX  ADM_CHECKLIST_MATRIX_IDX1 ON ADM_CHECKLIST_MATRIX(CLITEM_CODE);
ALTER TABLE ADM_CHECKLIST_MATRIX ADD CONSTRAINT ADM_CHECKLIST_MATRIX_PK PRIMARY KEY (CLGROUP_CODE, CLITEM_CODE)
USING INDEX ADM_CHECKLIST_MATRIX_IDX  ENABLE;

COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLI_ID IS 'ID matrix checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.PRC_CODE IS 'Mã quy trình';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLGROUP_CODE IS 'Mã Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_CODE IS 'Mã checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_NAME IS 'Tên checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_STATUS IS 'Trạng thái item checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLIGROUP_STATUS IS 'Trạng thái nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.USER_CREATED IS 'Người tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.DATE_CREATED IS 'Ngày tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.USER_UPDATED IS 'Người cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.DATE_UPDATED IS 'Ngày cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLIGM_STATUS IS 'Trạng thái item checklist matrix';
