CREATE SEQUENCE ADM_CHECKLIST_MATRIX_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;		
CREATE TABLE ADM_CHECKLIST_MATRIX ( 
CLI_ID NUMBER DEFAULT ADM_CHECKLIST_MATRIX_SEQ.NEXTVAL,
PRC_CODE	VARCHAR2(20),
CLGROUP_CODE VARCHAR2(50),
CLITEM_CODE VARCHAR2(50),
CLITEM_NAME NVARCHAR2(255),
CLIGM_STATUS	NUMBER,
CLITEM_STATUS NUMBER,
CLIGROUP_STATUS NUMBER,
USER_CREATED VARCHAR2(50),
DATE_CREATED DATE,
USER_UPDATED VARCHAR2(50),
DATE_UPDATED DATE,
CONSTRAINT ADM_CHECKLIST_MATRIX_FK1 FOREIGN KEY (PRC_CODE, CLGROUP_CODE)
        REFERENCES ADM_CHECKLIST_GROUP (PRC_CODE, CLGROUP_CODE) ,
CONSTRAINT ADM_CHECKLIST_MATRIX_FK2 FOREIGN KEY (CLITEM_CODE)
        REFERENCES ADM_CHECKLIST_ITEM (CLITEM_CODE)         
);
CREATE INDEX  ADM_CHECKLIST_MATRIX_IDX ON ADM_CHECKLIST_MATRIX(CLGROUP_CODE, CLITEM_CODE);
CREATE INDEX  ADM_CHECKLIST_MATRIX_IDX1 ON ADM_CHECKLIST_MATRIX(CLITEM_CODE);
ALTER TABLE ADM_CHECKLIST_MATRIX ADD CONSTRAINT ADM_CHECKLIST_MATRIX_PK PRIMARY KEY (CLGROUP_CODE, CLITEM_CODE)
USING INDEX ADM_CHECKLIST_MATRIX_IDX  ENABLE;

COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLI_ID IS 'ID matrix checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.PRC_CODE IS 'Mã quy trình';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLGROUP_CODE IS 'Mã Nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_CODE IS 'Mã checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_NAME IS 'Tên checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLITEM_STATUS IS 'Trạng thái item checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLIGROUP_STATUS IS 'Trạng thái nhóm checklist';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.USER_CREATED IS 'Người tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.DATE_CREATED IS 'Ngày tạo';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.USER_UPDATED IS 'Người cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.DATE_UPDATED IS 'Ngày cập nhật';
COMMENT ON COLUMN SAALEM.ADM_CHECKLIST_MATRIX.CLIGM_STATUS IS 'Trạng thái item checklist matrix';
---
## Insert Sample
Insert into ADM_CHECKLIST_MATRIX (CLI_ID,CLGROUP_TYPE,CLGROUP_CODE,CLITEM_CODE,CLITEM_NAME,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED,CLIGM_STATUS) values (44,'LOAINHOMCL05','QD13_KHCN_05','QD13_KHCN_05_04','Biên nhận đã thanh toán/ Xác nhận đã thanh toán công nợ của bên bán hàng (nếu có).','hanhtt',to_date('30-09-2024 13:59:50343','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:59:50343','DD-MM-YYYY HH24:MI:SSSSS'),1);
Insert into ADM_CHECKLIST_MATRIX (CLI_ID,CLGROUP_TYPE,CLGROUP_CODE,CLITEM_CODE,CLITEM_NAME,USER_CREATED,DATE_CREATED,USER_UPDATED,DATE_UPDATED,CLIGM_STATUS) values (46,'LOAINHOMCL05','QD13_KHCN_06','QD13_KHCN_06_02','Văn bản/ Hợp đồng chuyển nhượng BĐS có công chứng/ chứng thực theo quy định của Pháp luật (1)','hanhtt',to_date('30-09-2024 13:59:50343','DD-MM-YYYY HH24:MI:SSSSS'),'hanhtt',to_date('30-09-2024 13:59:50343','DD-MM-YYYY HH24:MI:SSSSS'),1);
## Dữ liệu khi cho bảng này là:

CLGN01 | Checklist Giải ngân / Phát hành bảo lãnh lần đầu | CLGN01_01 | Đề nghị giải ngân/phát hành cam kết bảo lãnh (nếu có)
QD13_KHCN_01 | Checklist Vay vốn lưu động-Giải ngân thanh toán theo hóa đơn mua hàng | QD13_KHCN_01_01 | Hóa đơn mua hàng (Hóa đơn VAT/ Hóa đơn điện tử/ Hóa đơn bán lẻ).